Algoritmo "parouimpar"
// Professor : Cintia pinho
// Descrição   : Verifica se o número digitado é par ou ímpar
// Autor(a)    : Maria Isadora
// Data atual  : 26/07/2022
var
numero: inteiro


Inicio
// entrada
escreval("Digite um número")
leia(numero)

//processamento
se (numero mod 2=0)entao
 escreval("O número é par")
senao
  escreval("O número é ímpar")
fimse


Fimalgoritmo