Algoritmo "Saquenobanco"
// Professor   : Cintia Pinho
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Maria Isadora
// Data atual  : 26/07/2022
Var
saldo,saque, limite:real
nome: caractere


Inicio
//entrada
escreval("Qual o seu nome?")
leia(nome)
escreval("Qual o valor que você irá sacar?")
leia(saque)
escreval("Qual o seu saldo?")
leia(saldo)

//processamento
saque<- (saldo-limite)

se (saldo

Fimalgoritmo