algoritmo "Habilitacao"
// Função : Descobre se a pessoa que possue 18 anos tem habilitação ou não
// Autor : Maria Isadora
// Data : 21/06/2022
// Seção de Declarações 
var
hab:caractere
idade:inteiro
id:logico
inicio
// Entrada
escreval("Digite sua idade")
leia(idade)
escreval("Você possui habilitação?")
leia(hab)

//processamento
id <-(idade>=18) e (hab="sim")

//saída
escreval("Você pode dirigir?",id)
fimalgoritmo
