algoritmo "EXE_1"
// Professor: Cintia Pinho
// Descrição:
// Autor(a): Maria Isadora
// Data atual: 01/11/2022
Var
// Seção de Declarações das variáveis
v: vetor[1..10] de inteiro
cont,numero,soma:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
 para cont:=1 ate 10 faca
 escreval("Digite o ",cont," número: ")
 leia(numero)
 soma <- soma + numero
 fimpara
escreval(" A soma de todos os números é: ",soma)
Fimalgoritmo
