algoritmo "Questao_1_ALG"
// Função :
// Autor :  Maria Isadora
// Data : 27/09/2022
// Seção de Declarações 
var
acu,num1,num2,cont,resp:inteiro
inicio
escreval("Digite o primeiro número")
leia(num1)
escreval("Digite o segundo número")
leia(num2)
escreval("Qual operação deseja realizar?")
leia(resp)
repita
cont<- cont+1
acu<- num1+num2
escreval("Estamos somando os números....",acu)
ate(resp=1000)



fimalgoritmo
