algoritmo "Cotacaodedolar "
// Função : Converte reais em dólar
// Autor : Maria Isadora
// Data : 26/04/2022
// Seção de Declarações 
var
cotdolar,conv,reais:real
inicio
//entrada
escreval("Digite o atual valor do dólar")
leia(cotdolar)
escreval("Qual valor você deseja converter?")
leia(reais)

//processamento
 conv<- reais/cotdolar
 
//saída
escreval("O valor da conversão sera de:",conv)
fimalgoritmo
