Algoritmo "fatorial"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Maria Isadora
// Data atual  : 20/09/2022
Var
numero,fator,cont:inteiro


Inicio
//entrada
fator<-1
escreval("Digite um número >0")
leia(numero)

para cont de numero ate 1 passo -1 faca
   fator<-fator*cont
fimpara

escreval("A fatoração de",num,"=",fator)

Fimalgoritmo