Algoritmo "numeros_impares"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Maria Isadora
// Data atual  : 06/09/2022
Var
cont:inteiro
nome:caractere

Inicio
// Entrada
escreval("olá,Qual o seu nome?")
leia(nome)
escreval("Vamos gerar os números ímpares!!")

//processamento
para cont de 100 ate 200 passo 2 faca
     escreval(cont)
fimpara

Fimalgoritmo