Algoritmo ""
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Cintia Pinho
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Maria Isadora
// Data atual  : 25/10/2022
Var
// Seção de Declarações das variáveis 
matrix: vetor[0..5.,0..6] de inteiro
andares, pessoas: inteiro



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  para 0 de 5 faca
  escreval("")


Fimalgoritmo